#!/usr/bin/sh

if which cargo-tarpaulin > /dev/null; then
	echo "cargo-tarpaulin found. Running tests and generating coverage report to `pwd`/target/tarpaulin/tarpaulin-report.html"
	cargo tarpaulin -o Html --output-dir `pwd`/target/tarpaulin
else
	echo "cargo-tarpaulin not found. Please install cargo-tarpaulin with \`cargo install cargo-tarpaulin\` and then try running this script again."
fi

